variables:
  APT_OPTIONS: -y --allow-unauthenticated

stages:
  - build

# Retry jobs after runner system failures
.retry: &retry
  retry:
    max: 2
    when:
      - runner_system_failure

build:
  stage: build
  image: debian:testing
  script:
    - apt-get update && apt-get $APT_OPTIONS install debos xz-utils bmap-tools
    - debos --scratchsize=4G rockpi4.yml
    - bmaptool create -o debian-rockpi4.bmap debian-rockpi4.img
    - xz -T0 debian-rockpi4.img
  artifacts:
    name: image
    paths:
      - $CI_PROJECT_DIR/debian-rockpi4.*
