variables:
  APT_OPTIONS: -y --allow-unauthenticated

stages:
  - build

# Retry jobs after runner system failures
.retry: &retry
  retry:
    max: 2
    when:
      - runner_system_failure

build:
  stage: build
  image: debian:testing
  script:
    - apt-get update && apt-get $APT_OPTIONS install debos pigz
    - debos --scratchsize=4G rockpi4.yml
    - pigz debian-rockpi4.img
  artifacts:
    name: debs
    paths:
      - $CI_PROJECT_DIR/*.img.gz
